version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5051:5051  # host:container
    networks:
      sample:
        aliases:
          - landing-service
  

  addition-service:
    build: ./addition
    hostname: addition-service
    ports:
      - 5052:5052
    networks:
      sample:
        aliases:
          - addition-service


  subtraction-service:
    build: ./subtraction
    hostname: subtraction-service
    ports:
      - 5053:5053
    networks:
      sample:
        aliases:
          - subtraction-service
  # Add more services below
networks:
  sample:
